import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();
  const { data, isLoading: isPostsLoading } = api.post.getAll.useQuery();
  let postContent;

  if (isPostsLoading) {
    postContent = <div>Loading...</div>;
  } else if (!data) {
    postContent = <div>Something went wrong...</div>;
  }

  if (data) {
    postContent = (
      <>
        {data?.map((post) => (
          <div className="mb-2 w-1/3" key={post.id}>
            <span>{post.title}</span>
            <p>{post.content}</p>
          </div>
        ))}
      </>
    );
  }
  return (
    <>
      <Head>
        <title>Reddit Light</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        data-theme="halloween"
        className="flex min-h-screen flex-col items-center justify-center"
      >
        {!isSignedIn && (
          <div>
            <SignInButton />
          </div>
        )}
        {user && (
          <div className="mb-3 flex flex-col items-center justify-center gap-3">
            <span>{user.username}</span>
          </div>
        )}
        {postContent}
      </main>
    </>
  );
};

export default Home;
