import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { user, isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!isSignedIn && (
          <div>
            <SignInButton />
          </div>
        )}
        {user && <span className="text-white">{user.username}</span>}
      </main>
    </>
  );
};

export default Home;
